[package]
name = "async_api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features =["full"]}
mediator = { path = "../../mediator", features=["async", "streams"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
